### ISSUE TITLE
No DID registered error with latest docker image

### ISSUE THREAD

**Issue by sudeshrshetty** [decentralized-identity/uni-registrar-driver-did-v1#2]
**How to reproduce:** 

```
curl -X POST 'http://localhost:9080/1.0/register?driverId=driver-universalregistrar%2Fdriver-did-v1' -d '{"options":{"ledger":"test","keytype": "ed25519"}}'

```

**Error in logs:**

```
[qtp1845746463-29] INFO servlet.RegisterServlet (doPost) - Incoming register request: {"jobId":"7a5bfe37-025f-40f8-9a8d-1c35ace268da","options":{"keytype":"ed25519","ledger":"test"},"secret":null,"didDocument":{"publicKey":[{"id":"P9ZaFHURBAlN5JrVd4eTV37co4jPwmVzcrdUr-jSwzg","type":"Ed25519VerificationKey2018","value":"umweICaKf3DcQeP9sJiuYG7R9luWlDHBgt2Ov6aRXG0=","purpose":["general","assertion","auth"],"encoding":"Jwk","keyType":"Ed25519"},{"id":"3khOXNXXF5zKyH_lsY-soIskGybhXy55IeD3Vnm1COg","type":"JwsVerificationKey2020","value":"cuax93LjlB++LwWrk2LqRHmmvrVkb28jSavVv+wzd8Y=","purpose":["general","assertion","auth"],"encoding":"Jwk","keyType":"Ed25519"},{"id":"RrlziQ4LfkrePHOoPpd7rpTaFdfnalQz7C_Ob4xTMqs","type":"JwsVerificationKey2020","value":"BD5S9Ng4rO8gTTNXs+L2yTZlQQdlhLIelmFPXypC4wycp8NsQvIzsYP469mo76BopNStoqFNMSkva/KH5hMpr+Q=","purpose":["general","assertion","auth"],"encoding":"Jwk","keyType":"P256"},{"id":"recovery-key","type":"JwsVerificationKey2020","value":"+ah5oWFHpTGVLZycSvlLXQJUHIEtqipuPrb8IiaQEx8=","encoding":"Jwk","recovery":true},{"id":"update-key","type":"JwsVerificationKey2020","value":"r/5iwmQhw4PTtpCUNNMMIyj3mNjTG3Y/Dr4NpMqzI1E=","encoding":"Jwk","update":true}]}}
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR: { Error: Cannot find module 'sodium-native'
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at Function.Module._resolveFilename (module.js:548:15)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at Function.Module._load (module.js:475:25)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at Module.require (module.js:597:17)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at require (internal/module.js:11:18)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at Function.generate (/opt/did-cli/node_modules/crypto-ld/lib/Ed25519KeyPair.js:145:22)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at Function.generate (/opt/did-cli/node_modules/crypto-ld/lib/LDKeyPair.js:78:31)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at VeresOneDidDoc.init (/opt/did-cli/node_modules/did-veres-one/lib/VeresOneDidDoc.js:166:35)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at Function.generate (/opt/did-cli/node_modules/did-veres-one/lib/VeresOneDidDoc.js:61:15)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at VeresOne.generate (/opt/did-cli/node_modules/did-veres-one/lib/VeresOne.js:191:27)
[qtp1845746463-29] WARN v1.DidV1Driver (register) - ERR:     at api.generate (/opt/did-cli/lib/drivers/veres/index.js:139:41) code: 'MODULE_NOT_FOUND' }
[qtp1845746463-29] WARN servlet.RegisterServlet (doPost) - Driver reported for {"jobId":"7a5bfe37-025f-40f8-9a8d-1c35ace268da","options":{"keytype":"ed25519","ledger":"test"},"secret":null,"didDocument":{"publicKey":[{"id":"P9ZaFHURBAlN5JrVd4eTV37co4jPwmVzcrdUr-jSwzg","type":"Ed25519VerificationKey2018","value":"umweICaKf3DcQeP9sJiuYG7R9luWlDHBgt2Ov6aRXG0=","purpose":["general","assertion","auth"],"encoding":"Jwk","keyType":"Ed25519"},{"id":"3khOXNXXF5zKyH_lsY-soIskGybhXy55IeD3Vnm1COg","type":"JwsVerificationKey2020","value":"cuax93LjlB++LwWrk2LqRHmmvrVkb28jSavVv+wzd8Y=","purpose":["general","assertion","auth"],"encoding":"Jwk","keyType":"Ed25519"},{"id":"RrlziQ4LfkrePHOoPpd7rpTaFdfnalQz7C_Ob4xTMqs","type":"JwsVerificationKey2020","value":"BD5S9Ng4rO8gTTNXs+L2yTZlQQdlhLIelmFPXypC4wycp8NsQvIzsYP469mo76BopNStoqFNMSkva/KH5hMpr+Q=","purpose":["general","assertion","auth"],"encoding":"Jwk","keyType":"P256"},{"id":"recovery-key","type":"JwsVerificationKey2020","value":"+ah5oWFHpTGVLZycSvlLXQJUHIEtqipuPrb8IiaQEx8=","encoding":"Jwk","recovery":true},{"id":"update-key","type":"JwsVerificationKey2020","value":"r/5iwmQhw4PTtpCUNNMMIyj3mNjTG3Y/Dr4NpMqzI1E=","encoding":"Jwk","update":true}]}}: No DID registered.
uniregistrar.RegistrationException: No DID registered.
	at uniregistrar.driver.did.v1.DidV1Driver.register(DidV1Driver.java:173)
	at uniregistrar.driver.servlet.RegisterServlet.doPost(RegisterServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sudeshrshetty** [comment]
@peacekeeper
